# Go development environment with bells and whistles
#
# docker build -f Dockerfile.dev -t gotools .
#
#

#==========================
FROM debian:jessie as build
#==========================

# Build and runtime deps
# Note: taking advantage of this being a multi-stage build. It's
# slightly slower than a single RUN command, but has the advantage
# that packages can be inserted and removed with less overall impace.
# Note also that it's not necessary to clean up the cache after.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
ARG APTARGS="-yq --no-install-recommends install"
RUN apt-get ${APTARGS} apt-utils
RUN apt-get ${APTARGS} autoconf
RUN apt-get ${APTARGS} automake
RUN apt-get ${APTARGS} build-essential
RUN apt-get ${APTARGS} ca-certificates
RUN apt-get ${APTARGS} curl
RUN apt-get ${APTARGS} cmake
RUN apt-get ${APTARGS} dnsutils
RUN apt-get ${APTARGS} gcc
RUN apt-get ${APTARGS} git
RUN apt-get ${APTARGS} iptables
RUN apt-get ${APTARGS} jq
RUN apt-get ${APTARGS} procps
RUN apt-get ${APTARGS} sudo
RUN apt-get ${APTARGS} tar
RUN apt-get ${APTARGS} unzip
RUN apt-get ${APTARGS} vim-common
RUN apt-get ${APTARGS} xfsprogs
RUN apt-get ${APTARGS} xz-utils

# Install Go
ARG GO_VERSION=1.8.3
RUN curl -fsSL "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" \
	| tar -xzC /usr/local
ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go
ENV CGO_LDFLAGS -L/lib

# Install protoc
ARG PROTOC_VERSION=3.3.0
RUN curl -fsSLo /tmp/protoc.zip "https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip" && \
    unzip /tmp/protoc.zip -d /tmp/protoc && \
    mv /tmp/protoc/bin/protoc /usr/local/bin && \
    rm -rf /tmp/protoc*
RUN go get github.com/golang/protobuf/proto
RUN go get github.com/golang/protobuf/protoc-gen-go
RUN go get github.com/gogo/protobuf/protoc-gen-gofast
RUN go get github.com/gogo/protobuf/protoc-gen-gogofast
RUN go get github.com/gogo/protobuf/protoc-gen-gogofaster
RUN go get github.com/gogo/protobuf/protoc-gen-gogoslick
RUN go get google.golang.org/grpc
RUN go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
RUN go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

RUN go get github.com/alecthomas/gometalinter
RUN gometalinter --install

# Move generated Go binaries to /usr/local/bin because only /usr/local/bin
# gets copied in the final stage. We do this for two reasons:
# 1. Keep /go/bin|pkg|src clean for the final stage for only vendored packages
# 2. Ensure executable binaries are always available, even in a login shell
RUN mv /go/bin/* /usr/local/bin

#==========================
from debian:jessie
#==========================

ENV GO_VERSION 1.8.3
ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go
ENV CGO_LDFLAGS -L/lib
ENV PROTOC_VERSION 3.3.0

COPY --from=build /usr/local/bin /usr/local/bin

WORKDIR /go
CMD [ "sh" ]

